# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#   find the sum of the even-valued terms.

def fibonacci_adder(num, num2, limit, holder=[])
  holder << num2 if num2.even?
  return holder.inject(:+) if num2 > limit
  fibonacci_adder(num2, num+num2, limit, holder)
end

p fibonacci_adder(1,2,4000000)



